#  DATA ACQUISTION

In [1]:
pip install yfinance pandas

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: yfinance in c:\users\ketki\appdata\roaming\python\python312\site-packages (1.2.1)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\ketki\appdata\roaming\python\python312\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (3.10.0)
Requirement already satisfied: pytz>=2022.5 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in c:\users\ketki\appdata\roaming\python\python312\site-packages (from yfinance) (4.0.4)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi>=0.15 in c:\users\ketki\appdata\roaming\python\python312\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (4.25.3)
Requirement already satisfied: websockets>=13.0 in c:\users\ketki\appdata\roaming\python\python312\site-packages (from yfinance) (16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=2.0.0 in c:\users\ketki\appdata\roaming\python\python312\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\programdata\anaconda3\lib\site-packages (from curl_cffi>=0.15->yfinance) (2025.1.31)
Requirement already satisfied: rich in c:\programdata\anaconda3\lib\site-packages (from curl_cffi>=0.15->yfinance) (13.7.1)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.2.3)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.21)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.0)

In [9]:
import pandas as pd
import yfinance as yf

In [6]:
df = pd.read_csv(r'C:\Users\ketki\OneDrive\Desktop\Infotact intern\stock.csv')

In [7]:
df

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,12/31/1965,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,01-03-1966,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,01-04-1966,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,01-05-1966,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,01-06-1966,532.070007,532.070007,532.070007,532.070007,532.070007,0.0
...,...,...,...,...,...,...,...,...
112452,N100,5/27/2021,1241.119995,1251.910034,1241.119995,1247.069946,1247.069946,379696400.0
112453,N100,5/28/2021,1249.469971,1259.209961,1249.030029,1256.599976,1256.599976,160773400.0
112454,N100,5/31/2021,1256.079956,1258.880005,1248.140015,1248.930054,1248.930054,91173700.0
112455,N100,06-01-2021,1254.609985,1265.660034,1254.609985,1258.579956,1258.579956,155179900.0
112456,N100,06-02-2021,1258.489990,1263.709961,1258.239990,1263.619995,1263.619995,148465000.0

In [8]:
df.head()

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,12/31/1965,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,01-03-1966,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,01-04-1966,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,01-05-1966,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,01-06-1966,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

# MERGING API

In [10]:
# Load old dataset
old_data = pd.read_csv("stock.csv")

# Fetch new data
new_data = yf.download("TCS.NS", start="2024-01-01", end="2025-01-01")

# Reset index (important)
new_data.reset_index(inplace=True)

# Combine datasets
updated_data = pd.concat([old_data, new_data])

# Remove duplicates
updated_data.drop_duplicates(subset="Date", inplace=True)

# Save updated dataset
updated_data.to_csv("updated_stock.csv", index=False)

[*********************100%***********************]  1 of 1 completed